services:
  nuxt-app:
    build:
      context: .
      args:
        - DATABASE_URL=file:/app/data/prod.db
    container_name: nuxt-url-shortener
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/db

volumes:
  sqlite_data: